import { collection, deleteDoc, doc, getDocs, setDoc, type Firestore } from "firebase/firestore";
import type { Bookmark, ReadingProgressEntry, ReadingProgressMap } from "@/api/schema";
import { bookmarkPathSegments, progressPathSegments, quizResultPathSegments } from "./paths";
import type { QuizResultDocument } from "./quiz-result";

/**
 * Every function here takes `uid: string | null` and no-ops (resolves
 * immediately, never touches `db`) when it's `null` — task-13 brief:
 * "Mọi thứ đang chạy khi chưa đăng nhập phải tiếp tục chạy... Đừng chặn đọc
 * bài hay thi thử sau login." Bookmarking, reading a lesson, and finishing
 * a quiz all work fully offline/signed-out already (local storage — see
 * personal-data.ts and cache.ts); Firestore sync is a side effect layered
 * on top for a signed-in user, never a precondition for the local action.
 * Every call site (post screen, quiz screen) does the local write
 * unconditionally and calls these as a best-effort extra step, same
 * `.catch(() => {})` pattern as `refresh()` in state/content.tsx.
 */

export async function syncBookmarkAdded(db: Firestore, uid: string | null, bookmark: Bookmark): Promise<void> {
  if (!uid) return;
  await setDoc(doc(db, ...bookmarkPathSegments(uid, bookmark.slug)), { savedAt: bookmark.savedAt });
}

export async function syncBookmarkRemoved(db: Firestore, uid: string | null, postSlug: string): Promise<void> {
  if (!uid) return;
  await deleteDoc(doc(db, ...bookmarkPathSegments(uid, postSlug)));
}

/** Fetches every bookmark doc under `users/{uid}/bookmarks` — used once, right after sign-in, to merge with the local list (see personal-data.ts's `mergeBookmarks`). Returns `[]` when signed out rather than throwing, same no-op convention as the writers above. */
export async function fetchRemoteBookmarks(db: Firestore, uid: string | null): Promise<Bookmark[]> {
  if (!uid) return [];
  const snapshot = await getDocs(collection(db, "users", uid, "bookmarks"));
  return snapshot.docs.map((docSnapshot) => ({
    slug: docSnapshot.id,
    savedAt: typeof docSnapshot.data().savedAt === "number" ? docSnapshot.data().savedAt : 0,
  }));
}

export async function syncReadingProgress(db: Firestore, uid: string | null, seriesSlug: string, entry: ReadingProgressEntry): Promise<void> {
  if (!uid) return;
  await setDoc(doc(db, ...progressPathSegments(uid, seriesSlug)), entry);
}

/** Same role as `fetchRemoteBookmarks`, for `users/{uid}/progress`. */
export async function fetchRemoteReadingProgress(db: Firestore, uid: string | null): Promise<ReadingProgressMap> {
  if (!uid) return {};
  const snapshot = await getDocs(collection(db, "users", uid, "progress"));
  const progress: ReadingProgressMap = {};
  for (const docSnapshot of snapshot.docs) {
    const data = docSnapshot.data();
    if (typeof data.lessonId === "string" && typeof data.lessonSlug === "string" && typeof data.updatedAt === "number") {
      progress[docSnapshot.id] = { lessonId: data.lessonId, lessonSlug: data.lessonSlug, updatedAt: data.updatedAt };
    }
  }
  return progress;
}

/**
 * Writes a finished quiz attempt's result to
 * `quizResults/{uid}/attempts/{attemptId}` — task-13 brief's own required
 * path. `attemptId` is generated by the caller (quiz screen, via
 * `expo-crypto`'s `randomUUID()`) rather than here, so a test can inject a
 * fixed id instead of asserting against a random one.
 */
export async function syncQuizResult(db: Firestore, uid: string | null, attemptId: string, result: QuizResultDocument): Promise<void> {
  if (!uid) return;
  await setDoc(doc(db, ...quizResultPathSegments(uid, attemptId)), result);
}
